services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Henahax
      POSTGRES_PASSWORD: "password"
    volumes:
      - /srv/container-volumes/postgres:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@test.com
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    volumes:
      - /srv/container-volumes/pgadmin:/var/lib/pgadmin

volumes:
  pgadmin_data:
    driver: local
    driver_opts:
      type: none
      device: /srv/container-volumes/pgadmin
      o: bind
