version: "3.9"

services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    restart: unless-stopped
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_postgresql
      TS3SERVER_DB_SQLCREATEPATH: create_postgresql
      TS3SERVER_DB_HOST: postgresql # service name of Postgres in the other stack
      TS3SERVER_DB_USER: "${TEAMSPEAK_DB_USER}"
      TS3SERVER_DB_PASSWORD: "${TEAMSPEAK_DB_PASSWORD}"
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    volumes:
      - teamspeak-data:/var/ts3server/
    networks:
      - postgres-network # external network to reach Postgres

  sinusbot:
    image: sinusbot/docker
    container_name: sinusbot
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    ports:
      - "8087:8087"
    volumes:
      - sinusbot-data:/opt/sinusbot/data
      - sinusbot-scripts:/opt/sinusbot/scripts

volumes:
  teamspeak-data:
    driver: local
    driver_opts:
      type: none
      device: /volumes/teamspeak
      o: bind
  sinusbot-data:
    driver: local
    driver_opts:
      type: none
      device: /volumes/sinusbot
      o: bind
  sinusbot-scripts:
    driver: local
    driver_opts:
      type: none
      device: /volumes/sinusbot/scripts
      o: bind

networks:
  postgres-network:
    external: true
