services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "9080:8080"
    volumes:
      - docker_sock:/var/run/docker.sock:ro
      - traefik_config:/etc/traefik/traefik.yml:ro
      - traefik_certs:/certs:ro
    restart: unless-stopped

volumes:
  docker_sock:
    driver: local
    driver_opts:
      type: none
      device: /var/run/docker.sock
      o: bind
  traefik_config:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/traefik/config/traefik.yml
      o: bind
  traefik_certs:
    driver: local
    driver_opts:
      type: none
      device: /container-volumes/traefik/certs
      o: bind
