services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # on host system
      - /mnt/zfs/docker/portainer_data:/data # bind mount to ZFS dataset
    ports:
      - 9443:9443
      # - 8000:8000 # Edge Agents
networks:
  default:
    name: portainer_network
