services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # bind socket directly
      - portainer_data:/data # persistent ZFS volume
    ports:
      - 9443:9443
      # - 8000:8000 # Edge Agents

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /srv/container-volumes/portainer
      o: bind

networks:
  default:
    name: portainer_network
