services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/zfs/docker/portainer_data:/data # Bind mount to ZFS dataset
    ports:
      - 9443:9443
      - 8000:8000 # Remove if you do not intend to use Edge Agents

# You can remove the volumes section entirely if you use bind mounts
# volumes:
#   portainer_data:
#     name: portainer_data

networks:
  default:
    name: portainer_network
