# https://docs.linuxserver.io/images/docker-joplin/
# postgres network

services:
  joplin:
    image: lscr.io/linuxserver/joplin:latest
    container_name: joplin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
