services:
  foldingathome:
    image: lscr.io/linuxserver/foldingathome:latest
    container_name: foldingathome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ACCOUNT_TOKEN=${FOLDINGATHOME_ACCOUNT_TOKEN}
      - MACHINE_NAME=${FOLDINGATHOME_MACHINE_NAME}
      - CLI_ARGS= #optional
    volumes:
      - foldingathome:/config
    ports:
      - 7396:7396 #optional
    restart: unless-stopped
volumes:
  foldingathome_data:
    driver: local
    driver_opts:
      type: none
      device: /volumes/foldingathome # Host path on your ZFS dataset
      o: bind
